# Site settings
title: Simple Portfolio
description: A Simple Portfolio for showcase and tinkering
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "http://codemagicspells.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Benzo Benno
user_description: ğŸ‘¨â€ğŸ’» CS undergrad @ CUSAT SOE | ğŸ” Cybersecurity explorer | ğŸ§ Linux tinkerer | Forever curious & always breaking (and fixing) things
user_title: Software Developer
email: benzoclay@gmail.com
twitter_username:
github_username:  codemagicspells
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
